name: showcase
description: A new Flutter project.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  counter_app:
    path: ../test_apps/counter_app
  weight_tracker:
    path: ../test_apps/weight_tracker
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/weight_tracker.png
    - assets/counter.png
