name: weight_tracker
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  framy_annotation: ^0.1.5
  device_preview: ^0.4.8
  provider: ^4.3.1
  intl: ^0.16.1
  freezed_annotation: ^0.11.0
  flutter_riverpod: ^0.5.1
  built_value: ^7.1.0

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
  framy_generator:
    path: ../../framy_generator
  flutter_driver:
    sdk: flutter
  test: any
  ozzie: ^2.2.3
  freezed: ^0.11.0
  built_value_generator: ^7.1.0

#dependency_overrides:
#  freezed_annotation: ^0.11.0 #device preview uses old version
#  freezed: ^0.11.2 #device preview uses old version
#  framy_annotation:
#    path: ../../framy_annotation

flutter:
  uses-material-design: true
