name: counter_app
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  framy_annotation: ^0.1.3
  device_preview: ^0.4.5

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
  framy_generator:
    path: ../../framy_generator
  flutter_driver:
    sdk: flutter
  test: any
  ozzie: ^2.2.3

flutter:
  uses-material-design: true
