name: framy_generator
description: A convenient code generator for app styleguide, gallery, wireframes and/or storyboard.
version: 0.1.0
homepage: https://github.com/Fidev-io/framy

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  build: ^1.3.0
  source_gen: ^0.9.5
  glob: ^1.2.0
  #  analyzer: ">=0.39.2 <0.40.0"

  framy_annotation:
    ^0.1.0
#    path: ../framy_annotation

dev_dependencies:
  build_runner: ^1.10.0
  test: any
  mockito: any
