name: framy_generator
description: A convenient code generator for app styleguide, gallery, storyboard and more.
version: 0.1.7
repository: https://github.com/Fidev-io/framy
homepage: https://framy.dev

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  build: ^1.3.0
  source_gen: ^0.9.5
  glob: ^1.2.0
  analyzer: ">=0.39.11 <0.40.0"
  framy_annotation: ^0.1.2
#    path: ../framy_annotation

dev_dependencies:
  build_runner: ^1.10.0
  test: any
  mockito: any
  source_gen_test:
    git:
      url: https://github.com/Fidev-io/source_gen_test.git
