name: framy_generator
description: A convenient code generator for app styleguide, gallery, storyboard and more.
version: 0.2.2
repository: https://github.com/Fidev-io/framy
homepage: https://framy.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  build: ^1.3.0
  source_gen: ^0.9.6
  glob: ^1.2.0
  analyzer: ">0.39.10 <=0.39.14"  #https://github.com/flutter/flutter/issues/56779
  framy_annotation: ^0.1.4
  yaml: ^2.2.1

dev_dependencies:
  build_runner: ^1.10.0
  test: any
  mockito: any
  source_gen_test:
    git:
      url: https://github.com/Fidev-io/source_gen_test.git

#dependency_overrides:
#  framy_annotation:
#    path: ../framy_annotation
