name: Generator tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  analyze-and-test-generator:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1.3.0
        with:
          channel: 'dev'
      - run: flutter pub get
        working-directory: framy_generator
      - run: flutter analyze
        working-directory: framy_generator
      - run: flutter test
        working-directory: framy_generator